version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    steps:
      - checkout
      - run: npm install
  test:
    steps:
      - checkout
      - run: npm test
workflows:
  version: 2
  buid_and_test:
    jobs:
      - build
      - test
